/* ============================================================
   前后端数据契约（DTO）— 类型从 Zod schema 推导（Milestone 2）
   来源：schemas.ts 是单一数据真值，本文件仅 re-export 类型名
   以保持 M1 导入路径兼容。
   ============================================================ */

export type {
  Currency,
  DataSource,
  DataStatus,
  Money,
  ApiEnvelope,
  PaginationParams,
  SystemStatus,
  MarketSession,
  RuntimeEnv,
  WarningStatus,
  LifecycleStage,
  OrderStatus,
  ReconciliationStatus,
  PositionType,
  EntryType,
  SignalDirection,
  PlanStatus,
  SleeveKey,
  BacktestStatus,
  StrategyMarket,
  StrategyFrequency,
  SystemIssue,
  SystemHealth,
  AccountSnapshot,
  RiskBudget,
  RiskSleeve,
  ExposureSummary,
  ConcentrationRisk,
  ThemeRisk,
  PortfolioRiskSummary,
  StrategySummary,
  StrategyFilter,
  BacktestRunSummary,
  BacktestFilter,
  BacktestTradeSample,
  BacktestOrderLedgerItem,
  BacktestRunDetail,
  OrderIntent,
  BrokerOrder,
  Fill,
  ReconciliationIssue,
  OrderFilter,
  WarningItem,
  SignalCandidate,
  StrategyLifecycleSummary,
  BenchmarkPoint,
  BenchmarkSeries,
  DataQuality,
  OverviewData,
  OverviewScenario,
  /* Milestone 2.1 */
  AssetClass,
  Timeframe,
  Candle,
  CandleSeriesResponse,
  Instrument,
  SymbolSearchResult,
  MarketDataStatus,
  IndicatorDefinition,
  IndicatorInstance,
  BollingerBandPoint,
  RsiPoint,
} from './schemas'

export { ApiError, OVERVIEW_SCENARIOS, SCENARIO_LABELS } from './schemas'
